### ISSUE TITLE
PPG Model

### ISSUE THREAD

**Issue by EduardoPach** [lesterphillip/SVCC23_FastSVC#1]
Where's the PPG model mentioned in the README on how to train FastSVC?

**Comment by lesterphillip** [comment]
Hi, the PPG model is included in the repository.

https://github.com/lesterphillip/SVCC23_FastSVC/tree/main/harana/ppg/en_conformer_ctc_att

So, you just need to change `/path/to/dir`  in the configuration files to where you git-cloned the repo.

**Comment by EduardoPach** [comment]
Oh, thanks! My bad I saw that it's the same path in the config files. Also, does the current code support using a checking point to train?

**Comment by lesterphillip** [comment]
Yup! You can set the relative path of the checkpoint [in this line.](https://github.com/lesterphillip/SVCC23_FastSVC/blob/main/egs/svcc23/fastsvc1/run.sh#L23)
