### ISSUE TITLE
wav.scp 

### ISSUE THREAD

**Issue by mqmmwu** [lesterphillip/SVCC23_FastSVC#10]
I already generate the training set into folders IDM1, IDF1, CDM1, and CDF1 using script “https://github.com/lesterphillip/SVCC23_FastSVC/tree/main/egs/generate_dataset”,
but i still don’t know how to process the processed file into wav.scp format As stated in 2c in the link "https://github.com/lesterphillip/SVCC23_FastSVC/blob/main/egs/svcc23/baseline02/README.md"

**Comment by lesterphillip** [comment]
Sorry, that's my fault and the data prep code is incomplete. I'll try to post the updates in the next few days.

**Comment by lesterphillip** [comment]
In the meantime, you can refer to this code snippet.

https://github.com/lesterphillip/SVCC23_FastSVC/issues/6#issuecomment-1495766034

**Comment by mqmmwu** [comment]
thank you so much for your reply
